dist: xenial
language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
env:
  - MKPROJ_LANG="generic"
  - MKPROJ_LANG="python"

# command to install dependencies
install:
  - pip install -r ci-requirements.txt
  - python setup.py -q install

# command to run tests
script:
  - flake8
  - mkproj -l $MKPROJ_LANG "$MKPROJ_LANG_proj"
